name: Type Check (on Commit)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  mypy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-typecheck.txt

      - name: Write Public Key
        run: python launch.py --write-public-key

      - name: Run Mypy
        run: |
          python -m mypy launch.py launcher.py --disallow-untyped-defs --disallow-incomplete-defs
